# Generated by Django 5.0.7 on 2025-01-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preorder',
            name='current',
            field=models.BooleanField(default=True),
        ),
    ]
