# Generated by Django 5.0.7 on 2025-01-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersignup',
            name='verification_token',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='newslettersignup',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
