# Generated by Django 4.2 on 2024-11-29 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HusbandrySystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=254)),
                ('box_height_mm', models.PositiveIntegerField(default=0)),
                ('box_depth_mm', models.PositiveIntegerField(default=0)),
                ('box_width_mm', models.PositiveIntegerField(default=0)),
                ('frame_height_mm', models.PositiveIntegerField(default=0)),
                ('frame_depth_mm', models.PositiveIntegerField(default=0)),
                ('frame_width_mm', models.PositiveIntegerField(default=0)),
                ('description', models.TextField()),
            ],
        ),
    ]
