# Generated by Django 4.2 on 2024-11-29 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('husbandry_system', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='husbandrysystem',
            old_name='box_depth_mm',
            new_name='box_length_mm',
        ),
        migrations.RenameField(
            model_name='husbandrysystem',
            old_name='box_height_mm',
            new_name='depth_deep_mm',
        ),
        migrations.RenameField(
            model_name='husbandrysystem',
            old_name='frame_depth_mm',
            new_name='depth_medium_mm',
        ),
        migrations.RenameField(
            model_name='husbandrysystem',
            old_name='frame_height_mm',
            new_name='depth_shallow_mm',
        ),
        migrations.RemoveField(
            model_name='husbandrysystem',
            name='frame_width_mm',
        ),
        migrations.AlterField(
            model_name='husbandrysystem',
            name='name',
            field=models.CharField(max_length=254),
        ),
    ]
