# Generated by Django 4.2 on 2024-11-29 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('husbandry_system', '0002_rename_box_depth_mm_husbandrysystem_box_length_mm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='husbandrysystem',
            name='depth_deep_mm',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='husbandrysystem',
            name='depth_medium_mm',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='husbandrysystem',
            name='depth_shallow_mm',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
