# Generated by Django 5.0.7 on 2025-01-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='current',
            field=models.BooleanField(default=True),
        ),
    ]
